name: robusta_runner
homepage: https://robusta.covalab.io
repository: https://github.com/covalab/robusta
issue_tracker: https://github.com/covalab/robusta/issues
description: Run and extend your apps base on Riverpod, event driven, extensions, and more.
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  riverpod: ^2.2.0
  logger: ^1.2.0
  robusta_events: ^0.1.0
  meta: ^1.8.0

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^4.0.0
