name: robusta_firebase_messaging
homepage: https://robusta.covalab.io
repository: https://github.com/covalab/robusta
issue_tracker: https://github.com/covalab/robusta/issues
description: Providing bridge to integrate Robusta with Firebase Cloud Messaging features.
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  firebase_messaging: ^14.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  flutter_robusta_auth: ^0.1.0
  meta: ^1.8.0
  robusta_firebase_core: ^0.1.0
  robusta_runner: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
