name: flutter_robusta_hive
version: 0.1.0
homepage: https://robusta.covalab.io
repository: https://github.com/covalab/robusta
issue_tracker: https://github.com/covalab/robusta/issues
description: Providing bridge to integrate Robusta with Hive storage features.

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  robusta_runner: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
  path_provider_platform_interface: ^2.0.6
  path_provider: ^2.0.14
  plugin_platform_interface: ^2.1.4