name: flutter_robusta_firebase_core_example
description: Flutter Robusta Firebase Core example.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_robusta:
  robusta_firebase_core:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
