name: flutter_robusta_auth_example
description: Flutter Robusta Auth example.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_robusta:
  flutter_robusta_auth:

dev_dependencies:
  very_good_analysis: ^4.0.0
