name: flutter_robusta_auth
homepage: https://robusta.covalab.io
repository: https://github.com/covalab/robusta
issue_tracker: https://github.com/covalab/robusta/issues
description: Robusta auth extension for securing app purposes.
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  flutter_robusta: ^0.2.0
  go_router_plus: ^4.1.1
  meta: ^1.8.0
  robusta_runner: ^0.2.0+1

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  very_good_analysis: ^3.1.0
