name: flutter_robusta_auth
description: Robusta auth extension for securing app purposes.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  flutter_robusta: ^0.1.0
  go_router_plus: ^4.1.1
  meta: ^1.8.0
  robusta_runner: ^0.1.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  very_good_analysis: ^3.1.0
