name: flutter_robusta_cli
description: Robusta CLI help to build and generate codes for your apps.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.4.0
  logger: ^1.3.0
  riverpod: ^2.3.0
  robusta_runner: ^0.2.0

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1

executables:
  flutter_robusta_cli: robusta