name: robusta_dio
version: 0.0.0
homepage: https://robusta.covalab.io
repository: https://github.com/covalab/robusta
issue_tracker: https://github.com/covalab/robusta/issues
description: Robusta extension for integrating Dio features.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^5.1.1
  riverpod: ^2.3.0
  robusta_runner: ^0.2.0

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1
