name: 'Tests'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          architecture: x64
      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV
      - name: Install dependencies
        run: flutter pub get
      - name: Install Melos
        run: flutter pub global activate melos
      - name: Bootstrap
        run: melos bootstrap
      - name: Analyze
        run: melos analyze
      - name: Tests
        run: melos test
      - uses: codecov/codecov-action@v3
        with:
          # https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954
          token: ${{ secrets.CODECOV_TOKEN }}